name: Release

on:
  push:
    branches:
      - main

jobs:
  version:
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v4
        id: release-please
        with:
          release-type: node
    outputs:
      release_created: ${{ steps.release-please.outputs.release_created }}

  publish:
    runs-on: ubuntu-latest
    needs: [version]
    if: ${{ needs.version.outputs.release_created }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup environment
        uses: ./.github/actions/setup
      - name: Build
        run: pnpm build
      - name: Publish to NPM
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
